version: '3.8'

services:
  config-server:
    image: config-server:latest
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - eLearning-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  discovery-server:
    image: discovery-server:latest
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - eLearning-network
    depends_on:
      - config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  user-service:
    image: user-service:latest
    build:
      context: ./user-service
    ports:
      - "8086:8086"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  course-service:
    image: course-service:latest
    build:
      context: ./course-service
    ports:
      - "8082:8082"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  payment-service:
    image: payment-service:latest
    build:
      context: ./payment-service
    ports:
      - "8083:8083"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  rating-service:
    image: rating-service:latest
    build:
      context: ./rating-service
    ports:
      - "8084:8084"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  notification-service:
    image: notification-service:latest
    build:
      context: ./notification-service
    ports:
      - "8085:8085"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  eLearning-network:
    driver: bridge
