version: '3.7'
services:
  config-server:
    image: config-server:latest
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - eLearning-network

  discovery-server:
    image: discovery-server:latest
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - eLearning-network
    depends_on:
      - config-server

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server

  user-service:
    image: user-service:latest
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  course-service:
    image: course-service:latest
    build:
      context: ./course-service
    ports:
      - "8082:8082"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  payment-service:
    image: payment-service:latest
    build:
      context: ./payment-service
    ports:
      - "8083:8083"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rating-service:
    image: rating-service:latest
    build:
      context: ./rating-service
    ports:
      - "8084:8084"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notification-service:
    image: notification-service:latest
    build:
      context: ./notification-service
    ports:
      - "8085:8085"
    networks:
      - eLearning-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  eLearning-network:
    driver: bridge
