server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/ratings/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
